entrenamiento/entrenamiento/urls.py
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('reportes.urls')),
    url(r'^profesores/', include('profesores.urls')),
    url(r'^estudiantes/', include('estudiantes.urls')),
    url(r'^calificaciones/', include('calificaciones.urls')),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'inicio'}, name='logout'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entrenamiento/estudiantes/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('estudiantes.views',
    url(r'^crear/', 'crear', name='estudiante_crear'),
    url(r'^listar/', 'listar', name='estudiantes_listar'),
    url(r'^editar/(\d+)$', 'editar', name='estudiante_editar'),
    url(r'^cambiar/(\d+)$', 'cambiar_estado', name='estudiante_estado'),
)

entrenamiento/reportes/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static


urlpatterns = patterns(
    'reportes.views',
    url(r'^$', 'mostrar_inicio', name='index'),
    url(r'^inicio$', 'mostrar_inicio', name = 'inicio'),
    url(r'^reportes/barras', 'mostrar_grafica_barras', name='grafica_barras'),
    url(r'^reportes/actualizar', 'actualizar_reporte', name='actualizar_reporte'),
    url(r'^reportes/nota/', 'reporte_nota', name='reporte_nota')

)

entrenamiento/estudiantes/models.py
from django.db import models

# Create your models here.
class Estudiante(models.Model):

    TIPO_DOCUMENTO=(
        ('TI', 'Tarjeta de Identidad'),
        ('CC', 'Cédula de Ciudadania'),
        ('PS', 'Pasaporte'),

    )
    ESTADO =(
        (1, 'ACTIVO'),
        (0, 'INACTIVO'),
    )

    nombre = models.CharField(max_length=100, verbose_name="Nombre")
    apellidos = models.CharField(max_length=100, verbose_name="Apellidos")
    fecha_nacimiento = models.DateField(verbose_name="Fecha de Nacimiento")
    tipo_documento= models.CharField(max_length=20, choices=TIPO_DOCUMENTO, verbose_name="Tipo de identificación")
    identificacion= models.CharField(max_length=20, verbose_name="Número de identificación", unique=True)
    foto= models.ImageField(upload_to='fotos_estudiantes', blank=True, default='fotos_estudiantes/default.jpg')
    estado = models.IntegerField(choices=ESTADO, default=1)

    def __str__(self):
        return self.nombre + " "+self.apellidos

entrenamiento/estudiantes/forms.py
import datetime
from django import forms
from estudiantes.models import Estudiante
from entrenamiento.utilities import MyDateWidget

TIPO_DOCUMENTO=(
        ('TI', 'Tarjeta de Identidad'),
        ('CC', 'Cedula de Ciudadania'),
        ('PS', 'Pasaporte'),

)

class FormularioCrear(forms.ModelForm):


    def __init__(self, *args, **kwargs):
        super(FormularioCrear, self).__init__(*args, **kwargs)

    class Meta:
        model = Estudiante
        exclude = ('estado',)
        widgets = {
            'fecha_nacimiento': MyDateWidget(),
        }

    def clean(self):
        cleaned_data = super(FormularioCrear, self).clean()
        if not self._errors:
            try:
                fecha_nacimiento = cleaned_data.get('fecha_nacimiento')
            except Exception:
                fecha_nacimiento = None

            fecha_actual = datetime.date.today()
            if fecha_nacimiento:
                if fecha_nacimiento > fecha_actual:
                    mensaje = 'Esta no es una fecha de nacimiento valida. Debe ser antes de la fecha actual'
                    self.add_error('fecha_nacimiento', mensaje)
                else:
                    return cleaned_data
            else:
                return cleaned_data

        return cleaned_data


class FormularioEditar(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(FormularioEditar, self).__init__(*args, **kwargs)
        self.fields['tipo_documento'].widget.attrs['readonly'] = 1
        self.fields['identificacion'].widget.attrs['readonly'] = 1

    class Meta:
        model = Estudiante
        exclude = ('estado',)
        widgets = {
            'fecha_nacimiento': MyDateWidget(),
        }
    def clean(self):
        cleaned_data = super(FormularioEditar, self).clean()
        if not self._errors:
            try:
                fecha_nacimiento = cleaned_data.get('fecha_nacimiento')
            except Exception:
                fecha_nacimiento = None

            fecha_actual = datetime.date.today()
            if fecha_nacimiento:
                if fecha_nacimiento > fecha_actual:
                    mensaje = 'Esta no es una fecha de nacimiento valida. Debe ser antes de la fecha actual'
                    self.add_error('fecha_nacimiento', mensaje)
                else:
                    return cleaned_data
            else:
                return cleaned_data

        return cleaned_data

entrenamiento/estudiantes/views.py
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from estudiantes.forms import FormularioCrear, FormularioEditar
from estudiantes.models import Estudiante

@login_required
def crear(request):
    if request.method == 'POST':
        form = FormularioCrear(request.POST, request.FILES) #Se agrega el FILES para lograr carghar los archivos
        if form.is_valid():
            form.save()
            messages.success(request, "Estudiante guardado correctamente.")
            return redirect('estudiantes_listar')
    else:
        form= FormularioCrear()

    return render(request, 'crear_estudiante.html', {'form': form})

def listar(request):
    estudiantes = Estudiante.objects.all()

    return render(request, 'listar_estudiantes.html', {'lista': estudiantes})

@login_required
def editar(request, estudiante_id):
    try:
        estudiante = Estudiante.objects.get(pk=estudiante_id)
    except:
        estudiante = None
        return redirect('estudiantes_listar')
    form = FormularioEditar(instance=estudiante)
    if request.method == 'POST':
        form = FormularioEditar(request.POST, request.FILES, instance=estudiante)
        if form.is_valid():
            form.save()
            messages.success(request, "Datos de %s guardados correctamente.")%(estudiante.nombre)
            return redirect('estudiantes_listar')

    else:
        form = FormularioEditar(instance=estudiante)


    return render(request, 'editar_estudiante.html', {'form':form})

@login_required
def cambiar_estado(request, estudiante_id):
    try:
        estudiante = Estudiante.objects.get(pk=estudiante_id)
        if estudiante.estado == 0:
            estudiante.estado = 1
            estudiante.save()
            messages.success(request, "Se ha cambiado el estado del estudiante %s")%(estudiante.nombre)
        else:
            estudiante.estado = 0
            estudiante.save()
            messages.success(request, "Se ha cambiado el estado del estudiante %s")%(estudiante.nombre)
    except:
        estudiante = None
        return redirect('estudiantes_listar')

    return redirect('estudiantes_listar')

entrenamiento/estudiantes/templates/crear_estudiante.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block miga_pan %}
    <li><a href="/inicio">Inicio</a></li>
    <li><a href="">Estudiantes</a>
    <li class="active">Registrar</li>
{% endblock %}

{% block titulo_pagina %}
    Gestionar Estudiante
{% endblock %}

{% block titulo %}
                    <h2>Registar Estudiante</h2>
{% endblock %}


{% block contenido %}
    <div class="col-lg-8 col-lg-offset-2">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Registrar Estudiante</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <!-- Se añade el multipart para encriptar los archivos -->
                <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data" id="estudiante-form">{% csrf_token %}
                    <div >

                        <div >
                            {% bootstrap_field form.nombre layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.apellidos layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.fecha_nacimiento layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.tipo_documento layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.identificacion layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.foto layout="horizontal" %}
                        </div>
                    </div>
                   <center> {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary"%}</center>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script src="{{ STATIC_URL }}js/validaciones/validacion-estudiante.js"></script>
{% endblock %}

entrenamiento/estudiantes/templates/editar_estudiante.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block miga_pan %}
    <li><a href="/inicio">Inicio</a></li>
    <li><a href="">Estudiantes</a>
    <li class="active">Editar</li>
{% endblock %}

{% block titulo_pagina %}
    Gestionar Estudiante
{% endblock %}


{% block titulo %}
    <h2>Editar estudiante</h2>
{% endblock %}

{% block contenido %}
    <div class="col-lg-8 col-lg-offset-2">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Editar Estudiante</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <!-- Se añade el multipart para encriptar los archivos -->
                <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data" id="estudiante-form">{% csrf_token %}
                    <div >
                        <div >
                            {% bootstrap_field form.nombre layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.apellidos layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.fecha_nacimiento layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.tipo_documento layout="horizontal" %}
                        </div>
                        <input type="text" hidden id="select_documento">
                        <div >
                            {% bootstrap_field form.identificacion layout="horizontal" %}
                        </div>
                        <div >
                            {% bootstrap_field form.foto layout="horizontal" %}
                        </div>
                    </div>
                   <center> {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary"%}</center>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}js/validaciones/validacion-estudiante.js"></script>
    <script>

    $(document).ready(function(){
        $("select").css("pointer-events", "none");
    });
    </script>
{% endblock %}

entrenamiento/estudiantes/templates/listar_estudiantes.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block css %}
<!-- Data Tables -->
    <link href="{{ STATIC_URL }}css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

    <style>
    body.DTTT_Print {
        background: #fff;

    }
    .DTTT_Print #page-wrapper {
        margin: 0;
        background:#fff;
    }

    button.DTTT_button, div.DTTT_button, a.DTTT_button {
        border: 1px solid #e7eaec;
        background: #fff;
        color: #676a6c;
        box-shadow: none;
        padding: 6px 8px;
    }
    button.DTTT_button:hover, div.DTTT_button:hover, a.DTTT_button:hover {
        border: 1px solid #d2d2d2;
        background: #fff;
        color: #676a6c;
        box-shadow: none;
        padding: 6px 8px;
    }

    .dataTables_filter label {
        margin-right: 5px;

    }
    </style>

{% endblock %}

{% block miga_pan %}
    <li><a href="/inicio">Inicio</a></li>
    <li><a href="">Estudiantes</a>
    <li class="active">Listar</li>
{% endblock %}

{% block titulo_pagina %}
    Gestionar Estudiante
{% endblock %}

{% block titulo %}
                    <h2>Listar estudiantes</h2>
{% endblock %}

{% block titulo_panel %}
Listar Estudiantes
{% endblock %}

{% block contenido_panel %}

    <table class="table table-striped table-bordered table-hover dataTables-estudiantes" >
        <thead>
            <tr>
                <th>Nombres</th>
                <th>Identificación</th>
                <th>Estado</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
        {% for estudiante in  lista  %}
            <tr class="gradeX">
                <td>{{ estudiante.nombre }} {{ estudiante.apellidos }}</td>
                <td>{{ estudiante.tipo_documento }}: {{ estudiante.identificacion }}
                </td>
                {% if estudiante.estado == 0 %}
                    <td><span class="label label-danger">{{ estudiante.get_estado_display }}</span></td>
                {% else %}
                    <td><span class="label label-primary">{{ estudiante.get_estado_display }}</span></td>
                {% endif %}

                <td>
                    <div class="btn-group">
                    <button data-toggle="dropdown" class="btn btn-success dropdown-toggle">Acción <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'estudiante_editar' estudiante.id %}">Editar</a></li>
                            <li><a data-toggle="modal" data-target="#modal-estado{{ estudiante.id }}" href="" class="font-bold">Cambiar estado</a></li>

                            <li class="divider"></li>
                        {% endif %}
                        <li><a data-toggle="modal" data-target="#myModal-{{ estudiante.id }}" href="#">Vista Previa</a></li>
                    </ul>
                    </div>
                </td>
            </tr>
            <!-- Modal -->

            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="modal-estado{{ estudiante.id }}">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4>¿Está seguro que desea cambiar de estado a este estudiante?</h4>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                            <a href="{% url 'estudiante_estado' estudiante.id %}" type="button" class="btn btn-primary" id="estado-estudiante" >Si</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="myModal-{{ estudiante.id }}" role="dialog" tabindex="-1">
                <div class="modal-dialog">
                <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Vista Previa</h4>
                        </div>
                        <div class="modal-body">


                            <img src="{{ MEDIA_URL }}{{ estudiante.foto }}" class="img-responsive" width="200" height="200">

                            <p><b>Nombre:</b> {{ estudiante.nombre }} {{ estudiante.apellidos }}</p>
                            <p><b>Identificación:</b> {{ estudiante.identificacion }}</p>
                            <p><b>Fecha de nacimiento:</b> {{ estudiante.fecha_nacimiento }}</p>




                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}


        </tbody>

    </table>
{% endblock %}
{% block js %}
    <!-- Data Tables -->
    <script src="{{ STATIC_URL }}js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/dataTables/dataTables.tableTools.min.js"></script>



    <script>
        $(document).ready(function() {
           $('.dataTables-estudiantes').dataTable({
                responsive: true,
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                    "sSwfPath": "js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
                }
            });
        });
    </script>
{% endblock %}