entrenamiento/entrenamiento/urls.py
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('reportes.urls')),
    url(r'^profesores/', include('profesores.urls')),
    url(r'^estudiantes/', include('estudiantes.urls')),
    url(r'^calificaciones/', include('calificaciones.urls')),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'inicio'}, name='logout'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entrenamiento/reportes/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static


urlpatterns = patterns(
    'reportes.views',
    url(r'^$', 'mostrar_inicio', name='index'),
    url(r'^inicio$', 'mostrar_inicio', name = 'inicio'),
    url(r'^reportes/barras', 'mostrar_grafica_barras', name='grafica_barras'),
    url(r'^reportes/actualizar', 'actualizar_reporte', name='actualizar_reporte'),
    url(r'^reportes/nota/', 'reporte_nota', name='reporte_nota')

)

entrenamiento/reportes/models.py
from django.db import models

# Create your models here.

entrenamiento/reportes/forms.py
from django import forms


class FormularioReporteBarras(forms.Form):

    def __init__(self, *args, **kwargs):
        super(FormularioReporteBarras, self).__init__(*args, **kwargs)
        self.fields['anio'].widget.attrs.update({'class': 'many'})

    anios = (
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
        (11, '11'),
    )

    anio = forms.MultipleChoiceField(choices=anios, label="Año", required=False)

class FormularioFiltros(forms.Form):
    def __init__(self, *args, **kwargs):
        super(FormularioFiltros, self).__init__(*args, **kwargs)
        self.fields['anio'].widget.attrs.update({'class': 'many'})
        self.fields['materia'].widget.attrs.update({'class': 'many'})

    materias = (
        ('Español', 'Español'),
        ('Matematicas', 'Matemáticas'),
        ('Biologia', 'Biología'),
        ('Sociales', 'Sociales'),
        ('Filosofia', 'Filosofía'),
        ('Informatica', 'Informática'),
        ('Deporte', 'Deporte'),
    )
    anios = (
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
        (11, '11'),
    )

    materia = forms.MultipleChoiceField(choices=materias, label='Materias', required=False)
    anio = forms.MultipleChoiceField(choices=anios, label="Año", required=False)

entrenamiento/reportes/views.py
from django.shortcuts import render
import json
from django.http import JsonResponse
from estudiantes.models import Estudiante
from calificaciones.models import Calificacion
from profesores.models import Profesor
from .forms import FormularioReporteBarras, FormularioFiltros
from django.db.models import Count


def mostrar_inicio(request):
    estudiantes = Estudiante.objects.all().count()
    profesores = Profesor.objects.all().count()
    return render(request, 'inicio.html', {'estudiantes':estudiantes, 'profesores':profesores})

def mostrar_grafica_barras(request):
    formulario = FormularioReporteBarras(request.POST)
    lista = Calificacion.objects.values('materia').filter(nota__gte = 3).annotate(cantidad=Count('materia'))
    return render(request, 'reporte_barras.html', {'aprobados':lista, 'formulario':formulario})

def actualizar_reporte(request):
    anios = request.GET.getlist('anios[]')
    print(anios)
    if not anios or anios[0] == '':
        data = Calificacion.objects.values('materia').filter(nota__gte = 3).annotate(cantidad=Count('materia'))
    else:
        data = Calificacion.objects.values('materia').filter(anio__in=anios).filter(nota__gte = 3).annotate(cantidad=Count('materia'))
    lista_final = {}
    lista_final['lista']=list(data)
    return JsonResponse(lista_final)

def reporte_nota(request):

    forms = FormularioFiltros()
    lista_estudiantes = {}
    materias = []
    anios = []
    if request.is_ajax():
        try:
            materias = request.POST.getlist('materias[]')
            anios = request.POST.getlist('anios[]')

            if materias[0]!='':
                if   anios[0]!='':
                    lista_estudiantes = generar_datos(materias, anios)
                    return JsonResponse(lista_estudiantes)
                else:
                    anios=None
                    lista_estudiantes = generar_datos(materias, anios)
                    return JsonResponse(lista_estudiantes)
            elif anios[0]!='':
                materias = None
                lista_estudiantes = generar_datos(materias, anios)
                return JsonResponse(lista_estudiantes)
            else:
                materias = None
                anios = None
                lista_estudiantes = generar_datos(materias, anios)
                return JsonResponse(lista_estudiantes)


        except Exception as e:
            print (e)
    else:
        lista_estudiantes = json.dumps(generar_datos(materias, anios))

    return render(request, 'reporte_estudiante.html', {'lista': lista_estudiantes, 'forms': forms})

def generar_datos(materias, anios):

    if materias and anios:
        lista = Calificacion.objects.filter(materia__in=materias, anio__in=anios).distinct('estudiante', 'materia', 'etiqueta')
    elif materias:

        lista = Calificacion.objects.filter(materia__in=materias).distinct('estudiante', 'materia', 'etiqueta')
    elif anios:
        lista = Calificacion.objects.filter(anio__in=anios).distinct('estudiante', 'materia', 'etiqueta')
    else:

        lista = Calificacion.objects.distinct('estudiante', 'materia', 'etiqueta')

    lista_estudiantes = []

    notas = {}
    notas['cantidad'] = lista.filter(etiqueta='D').count()
    notas['etiqueta']='Deficiente'
    lista_estudiantes.append(notas)

    notas = {}
    notas['cantidad'] = lista.filter(etiqueta='I').count()
    notas['etiqueta']='Insuficiente'
    lista_estudiantes.append(notas)

    notas = {}
    notas['cantidad'] = lista.filter(etiqueta='A').count()
    notas['etiqueta']='Aceptable'
    lista_estudiantes.append(notas)

    notas = {}
    notas['cantidad'] = lista.filter(etiqueta='S').count()
    notas['etiqueta']='Sopbresaliente'
    lista_estudiantes.append(notas)

    notas = {}
    notas['cantidad'] = lista.filter(etiqueta='E').count()
    notas['etiqueta']='Excelente'
    lista_estudiantes.append(notas)

    lista_final = {}
    lista_final['lista_estudiantes']=lista_estudiantes

    return lista_final

entrenamiento/reportes/templates/reporte_barras.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block css %}
    <link href="{{STATIC_URL}}css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li>Reportes</li>
    <li class="'active'">Gráfica de barras</li>
{% endblock %}

{% block titulo_pagina %}
    Reporte de barras
{% endblock %}

{% block titulo %}
    <h2>Estudiantes aprobados por materia</h2>
{% endblock %}

{% block contenido %}

    <div class="col-lg-8 col-lg-offset-2">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Reporte de calificaciones</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <form id="FormularioReporteBarras" action="" method="POST" class="form-horizontal">
                    {% csrf_token %}
                    {% bootstrap_form formulario %}
                </form>
               <center> <div id="chartdiv" style="width: 640px; height: 350px;"></div> </center>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}js/amcharts/amcharts.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/amcharts/serial.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}js/select2.min.js"></script>

    <script type="text/javascript">
        $("select.many").select2({multiple:true});

        var data = {{ aprobados | safe }}

        //Crea grafica de barras
        var chart = new AmCharts.AmSerialChart();
        chart.dataProvider = data;
        chart.categoryField = "materia";

        var graph = new AmCharts.AmGraph();
        graph.valueField = "cantidad";
        graph.type = "column";
        graph.fillColors = "#0eafbd";
        graph.fillAlphas = 0.8;
        graph.lineAlpha = 0.5;
        graph.lineColor = "#69bdc9";

        chart.addGraph(graph);

        var categoryAxis = chart.categoryAxis;
        categoryAxis.autoGridCount  = false;
        categoryAxis.gridCount = data.length;
        categoryAxis.gridPosition = "start";
        //categoryAxis.labelRotation = 45;

        //Animación de la grafica
        chart.startDuration = 1;

        var valueAxis = new AmCharts.ValueAxis();
        //Los valores comienzan desde cero
        valueAxis.minimum = 0;
        chart.addValueAxis(valueAxis);

        //Despliega grafico en el div
        if (chart.dataProvider === undefined || chart.dataProvider.length === 0){
            chart.addLabel('50%', '50%', 'No se han encontrado datos', 'middle', 15, '#69bdc9');
        }else{
            chart.clearLabels();
        }

        chart.write('chartdiv');

        $('#id_anio').on('change', actualizarReporte);

        function actualizarReporte(){
            var anios = $(this).val();
            $.ajax(
                {
                    url:"{% url 'actualizar_reporte' %}",
                    type:'get',
                    data: {'anios[]': anios},
                    success: function(data){
                        chart.dataProvider = data.lista;
                        chart.validateData();

                        if (chart.dataProvider === undefined || chart.dataProvider.length === 0){
                            chart.addLabel('50%', '50%', 'No se han encontrado datos', 'middle', 15, '#69bdc9');
                        }else{
                            chart.clearLabels();
                        }
                    }
                }
            );
        }

    </script>

{% endblock %}

entrenamiento/reportes/templates/reporte_estudiante.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/amcharts/style.css" type="text/css">
    <link href="{{STATIC_URL}}css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block titulo %}
    <h1>Estudiantes por nota</h1>
{% endblock %}

{% block contenido %}
    <div class="col-lg-8 col-lg-offset-2">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Reporte de calificaciones</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                {% bootstrap_form forms %}
                <div id="chartdiv" style="width: 100%; height: 400px;"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}js/amcharts/amcharts.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/amcharts/pie.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/amcharts/themes/light.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/amcharts/datos_vacios.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}js/select2.min.js"></script>
<script>
    $("select.many").select2({multiple:true});

    var chart;
    var legend;



    var chartData = {{ lista | safe}};

    AmCharts.ready(function () {
        // PIE CHART
        chart = new AmCharts.AmPieChart(AmCharts.themes.light);
        chart.dataProvider = chartData.lista_estudiantes;
        chart.titleField = "etiqueta";
        chart.valueField = "cantidad";

        // LEGEND
        legend = new AmCharts.AmLegend();
        legend.align = "center";
        legend.markerType = "circle";
        chart.balloonText = "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>";
        chart.addLegend(legend);

        // WRITE

        chart.write("chartdiv");
        AmCharts.checkEmptyData(chart);



        $('#id_materia').on('change', function(event){

            var csrf_token = "{{ csrf_token }}";
            var materia = $("#id_materia").val();
            var anios = $("#id_anio").val();

            //console.log(anios);
            var url = "{% url 'reporte_nota' %}";

            $.ajax({
                type:"POST",
                url: url,
                data: {'materias[]': materia,'anios[]':anios, 'csrfmiddlewaretoken': csrf_token},
                dataType: 'json',
                success: function(data) {

                    chart.dataProvider = data.lista_estudiantes;
                    chart.validateData();
                    AmCharts.checkEmptyData(chart);
                }
                });
        });

        $('#id_anio').on('change', function(event){


            var csrf_token = "{{ csrf_token }}";
            var materia = $("#id_materia").val();
            var anios = $("#id_anio").val();

            var url = "{% url 'reporte_nota' %}";

            $.ajax({
                type:"POST",
                url: url,
                data: {'materias[]': materia,'anios[]':anios, 'csrfmiddlewaretoken': csrf_token},
                dataType: 'json',
                success: function(data) {
                    var datos = data.lista_estudiantes;
                    chart.dataProvider = datos;
                    chart.validateData();
                    AmCharts.checkEmptyData(chart);
                }
            });
        });

    });




</script>
{% endblock %}