entrenamiento/calificaciones/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('calificaciones.views',
    url(r'^registrar/', 'crear', name='calificacion_crear'),
    url(r'^listar/', 'listar', name='calificaciones_listar'),
    url(r'^editar/(\d+)$', 'editar', name='calificacion_editar'),
    url(r'^eliminar/(\d+)$', 'eliminar', name='calificacion_eliminar'),
)

entrenamiento/entrenamiento/urls.py
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('reportes.urls')),
    url(r'^profesores/', include('profesores.urls')),
    url(r'^estudiantes/', include('estudiantes.urls')),
    url(r'^calificaciones/', include('calificaciones.urls')),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'inicio'}, name='logout'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entrenamiento/reportes/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static


urlpatterns = patterns(
    'reportes.views',
    url(r'^$', 'mostrar_inicio', name='index'),
    url(r'^inicio$', 'mostrar_inicio', name = 'inicio'),
    url(r'^reportes/barras', 'mostrar_grafica_barras', name='grafica_barras'),
    url(r'^reportes/actualizar', 'actualizar_reporte', name='actualizar_reporte'),
    url(r'^reportes/nota/', 'reporte_nota', name='reporte_nota')

)

entrenamiento/calificaciones/models.py
from django.db import models
from profesores.models import Profesor
from estudiantes.models import Estudiante


class Calificacion(models.Model):

    etiquetas = (
        ('E', 'Excelente'),
        ('S', 'Sobresaliente'),
        ('A', 'Aceptable'),
        ('I', 'Insuficiente'),
        ('D', 'Deficiente'),
    )

    materias = (
        ('Español', 'Español'),
        ('Matematicas', 'Matemáticas'),
        ('Biologia', 'Biología'),
        ('Sociales', 'Sociales'),
        ('Filosofia', 'Filosofía'),
        ('Informatica', 'Informática'),
        ('Deporte', 'Deporte'),
    )

    profesor = models.ForeignKey(Profesor)
    estudiante = models.ForeignKey(Estudiante)
    nota = models.DecimalField(max_digits=2, decimal_places=1, verbose_name="Calificación")
    etiqueta = models.CharField(max_length=15, choices=etiquetas)
    anio = models.IntegerField(verbose_name="Año del estudiante")
    materia = models.CharField(max_length=30, choices=materias, verbose_name="Materia de calificación")
    descripcion = models.TextField(max_length=500, verbose_name="Observaciones", null=True)

entrenamiento/calificaciones/forms.py
from django import forms
from calificaciones.models import Calificacion

class FormularioCalificacion(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(FormularioCalificacion, self).__init__(*args, **kwargs)
        self.fields['nota'].widget.attrs.update({'max':5})
        self.fields['nota'].widget.attrs.update({'min':0})
        if self.instance.pk != None:
            self.fields['estudiante'].widget.attrs['readonly'] = 1
            self.fields['profesor'].widget.attrs['readonly'] = 1
            self.fields['materia'].widget.attrs['readonly'] = 1
            self.fields['anio'].widget.attrs['readonly'] = 1


    class Meta:
        model = Calificacion
        exclude= ('etiqueta',)

    def clean(self):
        cleaned_data = super(FormularioCalificacion, self).clean()

        if not self._errors:
            try:
                nota = cleaned_data.get('nota')
            except Exception:
                nota = None

            if nota:
                if nota > 5:
                    mensaje = "La nota no puede ser mayor a 5"
                    self.add_error('nota', mensaje)
                else:
                    return cleaned_data
            else:
                return cleaned_data
        return cleaned_data

entrenamiento/calificaciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from calificaciones.forms import FormularioCalificacion
from calificaciones.models import Calificacion
from django.contrib import messages

@login_required
def crear(request):
    if request.method == 'POST':
        form = FormularioCalificacion(request.POST)
        if form.is_valid():
            formulario = form.save(commit=False)
            nota = formulario.nota
            if nota < 2:
                formulario.etiqueta = 'D'
            elif nota < 3:
                formulario.etiqueta = 'I'
            elif nota < 4:
                formulario.etiqueta = 'A'
            elif nota < 5:
                formulario.etiqueta = 'S'
            else:
                formulario.etiqueta = 'E'
            messages.success(request, "Calificación guardada correctamente.")
            form.save()
            return redirect('calificaciones_listar')
    else:
        form=FormularioCalificacion()
    return render(request, 'registrar_calificacion.html', {'form': form, 'edicion': False})


@login_required
def editar(request, calificacion_id):
    try:
        calificacion = Calificacion.objects.get(pk=calificacion_id)
    except:
        calificacion = None
        return redirect('calificaciones_listar')
    form = FormularioCalificacion(instance=calificacion)
    if request.method == 'POST':
        form = FormularioCalificacion(request.POST, instance=calificacion)
        if form.is_valid():
            formulario = form.save(commit=False)
            nota = formulario.nota
            if nota < 2:
                formulario.etiqueta = 'D'
            elif nota < 3:
                formulario.etiqueta = 'I'
            elif nota < 4:
                formulario.etiqueta = 'A'
            elif nota < 5:
                formulario.etiqueta = 'S'
            else:
                formulario.etiqueta = 'E'
            messages.success(request, "Datos de la calificación guardados correctamente.")
            form.save()
            return redirect('calificaciones_listar')
    else:
        form = FormularioCalificacion(instance=calificacion)
    return render(request, 'registrar_calificacion.html', {'form':form, 'edicion': True})


def listar(request):
    calificaciones = Calificacion.objects.all()
    return render(request, 'listar_calificaciones.html', {'calificaciones': calificaciones})



@login_required
def eliminar(request, calificacion_id):
    try:
        calificacion = Calificacion.objects.get(pk=calificacion_id)
        calificacion.delete()
        messages.success(request, "La calificación ha sido eliminada.")
    except:
        calificacion = None
        return redirect('calificaciones_listar')
    return redirect('calificaciones_listar')

entrenamiento/calificaciones/templates/listar_calificaciones.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block css %}
<!-- Data Tables -->
    <link href="{{ STATIC_URL }}css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

    <style>
    body.DTTT_Print {
        background: #fff;

    }
    .DTTT_Print #page-wrapper {
        margin: 0;
        background:#fff;
    }

    button.DTTT_button, div.DTTT_button, a.DTTT_button {
        border: 1px solid #e7eaec;
        background: #fff;
        color: #676a6c;
        box-shadow: none;
        padding: 6px 8px;
    }
    button.DTTT_button:hover, div.DTTT_button:hover, a.DTTT_button:hover {
        border: 1px solid #d2d2d2;
        background: #fff;
        color: #676a6c;
        box-shadow: none;
        padding: 6px 8px;
    }

    .dataTables_filter label {
        margin-right: 5px;

    }
    </style>

{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li>Calificaciones</li>
    <li class="active">Listar</li>
{% endblock %}

{% block titulo %}
                    <h2>Consultar calificaciones de estudiantes</h2>
{% endblock %}

{% block titulo_panel %}
Listado de Calificaciones
{% endblock %}

{% block contenido_panel %}

    <table class="table table-striped table-bordered table-hover dataTables-calificaciones" >
        <thead>
            <tr>
                <th>Profesor</th>
                <th>Estudiante</th>
                <th>Materia</th>
                <th>Nota</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
        {% for calificacion in  calificaciones  %}
            <tr class="gradeX">
                <td>{{ calificacion.profesor }}</td>
                <td>{{ calificacion.estudiante }}</td>
                <td>{{ calificacion.materia }}</td>
                <td>{{ calificacion.nota }}</td>

                <td>
                    <div class="btn-group">
                    <button data-toggle="dropdown" class="btn btn-success dropdown-toggle">Acción <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'calificacion_editar' calificacion.id %}">Editar</a></li>
                        <li><a data-toggle="modal" data-target="#modal-estado{{ calificacion.id }}" href="" class="font-bold">Eliminar</a></li>

                        <li class="divider"></li>
                        <li><a data-toggle="modal" data-target="#myModal-{{ calificacion.id }}" href="#">Vista Previa</a></li>
                    </ul>
                    </div>
                </td>
            </tr>
            <!-- Modal -->

            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="modal-estado{{ calificacion.id }}">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4>¿Está seguro que desea eliminar esta calificación?</h4>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                            <a href="{% url 'calificacion_eliminar' calificacion.id %}" type="button" class="btn btn-primary" id="eliminar" >Si</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="myModal-{{ calificacion.id }}" role="dialog">
                <div class="modal-dialog">
                <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Vista Previa</h4>
                        </div>
                        <div class="modal-body">
                                    <p><b>Profesor:</b> {{ calificacion.profesor }} </p>
                                    <p><b>Estudiante:</b> {{ calificacion.estudiante }}</p>
                                    <p><b>Año:</b> {{ calificacion.anio }}</p>
                                    <p><b>Materia:</b> {{ calificacion.materia }}</p>
                                    <p><b>Nota:</b> {{ calificacion.nota }} {% if calificacion.etiqueta == 'D' %}
                                            <span class="label label-danger">{{ calificacion.get_etiqueta_display }}</span>
                                        {% elif calificacion.etiqueta == 'I' %}
                                            <span class="label label-warning">{{ calificacion.get_etiqueta_display }}</span>
                                        {% elif calificacion.etiqueta == 'A' %}
                                            <span class="label label-success">{{ calificacion.get_etiqueta_display }}</span>
                                        {% elif calificacion.etiqueta == 'S' %}
                                            <span class="label label-info">{{ calificacion.get_etiqueta_display }}</span>
                                        {% else %}
                                            <span class="label label-primary">{{ calificacion.get_etiqueta_display }}</span>
                                        {% endif %}</p>
                                    <p><b>Descripcion:</b> {{ calificacion.descripcion }}</p>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}


        </tbody>

    </table>
{% endblock %}
{% block js %}
    <!-- Data Tables -->
    <script src="{{ STATIC_URL }}js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/dataTables/dataTables.tableTools.min.js"></script>

    <script>
        $(document).ready(function() {
           $('.dataTables-calificaciones').dataTable({
                responsive: true,
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                    "sSwfPath": "js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
                }
            });
        });
    </script>
{% endblock %}

entrenamiento/calificaciones/templates/registrar_calificacion.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block titulo %}
    {% if edicion %}
    <h2>Editar Calificación</h2>
    {% else %}
    <h2>Registrar Calificación</h2>
    {% endif %}
{% endblock %}

{% block miga_pan %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li>Calificaciones</li>
    <li class="active">Registrar</li>
{% endblock %}

{% block contenido %}
    <div class="col-lg-8 col-lg-offset-2">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                {% if edicion %}
                <h5>Editar Calificación</h5>
                {% else %}
                <h5>Registrar Calificación</h5>
                {% endif %}
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <!-- Se añade el multipart para encriptar los archivos -->
                <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data" id="calificacion-form">{% csrf_token %}
                    {% bootstrap_field form.profesor layout='horizontal' %}
                    {% bootstrap_field form.estudiante layout='horizontal' %}

                    {% bootstrap_field form.nota  layout='horizontal' %}
                    <div class="form-group" id="etiqueta">
                        {% bootstrap_label "Deficiente" label_class='label-danger control-label col-md-3'%}
                    </div>



                    {% bootstrap_field form.anio layout='horizontal' %}
                    {% bootstrap_field form.materia layout='horizontal' %}
                    {% bootstrap_field form.descripcion layout='horizontal' %}
                    <center> {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary"%}</center>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}js/validaciones/validacion-calificacion.js"></script>
<script>
$(document).ready(function() {
    $("#id_nota").on('keyup', function () {

        if (isNaN($(this).val())) {
            alert("fallo");
        } else {
            var numero = parseFloat($(this).val())
            if (numero < 2) {
                document.getElementById("etiqueta").innerHTML = "<label class='label-danger control-label col-md-3'>Deficiente</label>";
            } else {
                if (numero < 3) {
                    document.getElementById("etiqueta").innerHTML = "<label class='label-warning control-label col-md-3'>Insuficiente</label>";
                } else {
                    if (numero < 4) {
                        document.getElementById("etiqueta").innerHTML = "<label class='label-success control-label col-md-3'>Aceptable</label>";
                    } else {
                        if (numero < 5) {
                            document.getElementById("etiqueta").innerHTML = "<label class='label-info control-label col-md-3'>Sobresaliente</label>";
                        } else {
                            if (numero == 5) {
                                document.getElementById("etiqueta").innerHTML = "<label class='label-primary control-label col-md-3'>Excelente</label>";
                            }else {
                                document.getElementById("etiqueta").innerHTML = "<label class='label control-label col-md-3'>Fuera de Rango</label>";
                            }
                        }
                    }
                }
            }
        }
    });
    {% if edicion %}
     $("select").css("pointer-events", "none");
    {% endif %}
});
</script>
{% endblock %}